#!/usr/bin/env bash

set -e

TOOL_SOURCE="${BASH_SOURCE[0]}"
while [ -h "$TOOL_SOURCE" ] ; do TOOL_SOURCE="$(readlink "$TOOL_SOURCE")"; done
HACK_DIR="$( cd -P "$( dirname "$TOOL_SOURCE" )" && pwd )"
PRJ_HOME="$( cd -P "$( dirname "$HACK_DIR" )" && pwd )"


source "${HACK_DIR}/config"
app_name="$GH_REPO"

SRC_DIR="${PRJ_HOME}/src"

[[ -d "${PRJ_HOME}/bin" ]] && rm -r "${PRJ_HOME}/bin"
[[ -d "${PRJ_HOME}/pkg" ]] && rm -r "${PRJ_HOME}/pkg"

hash gb 2>/dev/null || {
    go get -u github.com/constabulary/gb/...
}

export GOPATH="${PRJ_HOME}:${PRJ_HOME}/vendor"

cd "${PRJ_HOME}"

for dir in $(find "$SRC_DIR" -mindepth 1 -maxdepth 1 -type d); do
	app_name=$(basename "$dir")
    echo " =====     Process ${app_name} ${dir}     ====="
    cd "$dir"
	golint
	go fmt ./...
	go vet ./...
	goimports -w .
  # - diff <(goimports -d .) <(printf "")
  # - diff <(golint ./...) <(printf "")
    cd "$PRJ_HOME"
    gb build "$app_name"
    # echo "${d} go test -cpu=1,2,4 -race ./..."
	# go test -cpu=1,2,4 -race ./...
    cd "$dir"
    echo "${dir} go test -cover ./..."
	go test -cover ./...
    # echo "${d} go test show output"
	# go test -cover -v ./... -showoutput
done

# for dir in $(find "$SRC_DIR" -mindepth 1 -maxdepth 1 -type d); do
# 	echo " - Process $dir"
# 	bname=$(basename "$dir")
# 	echo $bname
# done
